### ISSUE TITLE
Regex in IntendedFor Checker

### ISSUE THREAD

**Issue by TinasheMTapera** [PennBBL/fw-heudiconv#41]
```WARNING: Trouble updating intentions for this session Session 2
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/aguirre/miniconda3/lib/python3.7/site-packages/fw_heudiconv/convert.py", line 231, in confirm_intentions
    ses_labs = [re.search(r"ses-[a-zA-z0-9]+(?=_)", x).group() for x in full_filenames if x is not None]
  File "/Users/aguirre/miniconda3/lib/python3.7/site-packages/fw_heudiconv/convert.py", line 231, in <listcomp>


    ses_labs = [re.search(r"ses-[a-zA-z0-9]+(?=_)", x).group() for x in full_filenames if x is not None]
AttributeError: 'NoneType' object has no attribute 'group'
(base) huntsman-ve703-05737:heudiDev aguirre$ 
```

Gotta find a nicer way to communicate this NoneType error

**Comment by TinasheMTapera** [comment]
de42a9a
