### ISSUE TITLE
sdk version not compatible with client

### ISSUE THREAD

**Issue by isabelannwingert** [PennBBL/fw-heudiconv#67]
```
Traceback (most recent call last):
  File "./fw_heudiconv_run.py", line 21, in <module>
    fw = flywheel.Flywheel(key)
  File "/usr/local/lib/python3.7/site-packages/flywheel/flywheel.py", line 69, in __init__
    raise Exception('Client user not expecting at least version 11 of'
Exception: Client user not expecting at least version 11 of the sdk'
```

Error above is what I get when attempting to run `curate`. I tried making my sdk compatible with my client, as well as having another user run the analysis I was attempting to run, but the same errors occurred:

```
python -c 'import flywheel; fw = flywheel.Client(); print(fw.get_version())'
``` 
gives me
```
/home/wingerti/opt/python-3.7.1/lib/python3.7/site-packages/flywheel/flywheel.py:6032: UserWarning: Client version 11.0.1 does not match server version 10.7.3. Please update your client version!
  warnings.warn('Client version {} does not match server version {}. Please update your client version!'.format(SDK_VERSION, release_version))
WARNING:Flywheel:Use "pip install flywheel-sdk~=10.7.3" to install a compatible version for this server
{'applied_fixes': {'fix_default_group_editions_67': '2019-10-10T02:15:58.746000+00:00',
                   'fix_move_flair_from_measurement_to_feature_66': '2019-08-31T04:29:37.053000+00:00',
                   'fix_parents_68': '2019-12-07T04:37:21.587000+00:00',
                   'fix_permission_recursion_67': '2019-10-26T03:31:39.944000+00:00',
                   'fix_subject_age_62': '2019-03-01T15:08:20.069000+00:00'},
 'cli_version': '10.7.3',
 'database': 69,
 'flywheel_release': '10.7.4',
 'id': 'version',
 'release': '10.7.3'}
```

**Comment by TinasheMTapera** [comment]
Fixed 29a22ae
